name: Build and Deploy Docker Image

on:
  push:
    branches: [main, master]
    paths:
      - "tp-microservices/api-musique/**"
  pull_request:
    branches: [main, master]
    paths:
      - "tp-microservices/api-musique/**"

env:
  DOCKER_IMAGE_NAME: api-musique
  DOCKER_REGISTRY: docker.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./tp-microservices/api-musique
          file: ./tp-microservices/api-musique/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trigger Render Deployment
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          if [ -n "${{ secrets.RENDER_DEPLOY_HOOK_URL }}" ]; then
            echo "Triggering Render deployment..."
            curl -X GET "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
            echo "Deployment triggered successfully"
          else
            echo "RENDER_DEPLOY_HOOK_URL not configured, skipping deployment trigger"
          fi
